/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
    domains: [
      'ext.same-assets.com',
      'same-assets.com',
      'images.unsplash.com',
      'via.placeholder.com',
      'media.graphassets.com',
      'p7.hiclipart.com',
      'images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com',
      'logos-download.com',
      'www.freepnglogos.com',
      'cmsassets.rgpub.io',
      'playvalorant.com',
      'valorantinfo.com',
      'res.cloudinary.com',
      'media.valorant-api.com',
      'media.giphy.com',
      'i.gifer.com',
      'is1-ssl.mzstatic.com',
      'i.imgur.com',
      'wallpapercave.com',
      'www.pngmart.com',
      'lolstatic-a.akamaihd.net',
      'i.pinimg.com',
      'static.wikia.nocookie.net',
      'yoolk.ninja',
      'static1.textcraft.net',
      'valorantstats.xyz',
      'riotgames.sng.link',
      'twitter.com',
      'www.youtube.com',
      'instagram.com',
      'tiktok.com',
      'www.facebook.com',
      'discord.gg',
      'media-cdn.incrowdsports.com',
    ],
  },
};

export default nextConfig;
